---
project:
  alias: homebrew-habitat

github:
  delete_branch_on_merge: true

subscriptions:
  - workload: project_promoted:{{agent_id}}:stable:*
    actions:
      - bash:.expeditor/scripts/bump_version.sh

