---
project:
  alias: homebrew-habitat

github:
  delete_branch_on_merge: true

subscriptions:
  - workload: habitat-sh/habitat:master_completed:project_promoted:habitat-sh/habitat:master:current:*
    actions:
      - bash:.expeditor/scripts/bump_version.sh

