---
project:
  alias: homebrew-habitat

github:
  delete_branch_on_merge: true

pipelines:
  - verify:
      description: Pull Request validation tests

subscriptions:
  - workload: habitat-sh/habitat:main_completed:project_promoted:habitat-sh/habitat:main:current:*
    actions:
      - bash:.expeditor/scripts/bump_version.sh
